# =======================================================
#       ditzz-devnest RDP Deployment Workflow v2.0
# =======================================================
# Deskripsi: Menggabungkan fitur input manual dan validasi
#            secret dengan skrip master yang sudah diperbaiki.
# Architect: ditzz-devnest
# =======================================================

name: ditzz-devnest RDP Deployment (v2)

on:
  workflow_dispatch:
    inputs:
      INSTANCE_LABEL:
        description: 'Label untuk sesi ini (opsional, misal: "sesi-gaming")'
        required: false
        default: 'default'

jobs:
  deploy:
    name: "Deploy RDP Instance [${{ github.event.inputs.INSTANCE_LABEL }}]"
    runs-on: windows-11-arm
    timeout-minutes: 360
    
    steps:
      - name: "[1] Validate Secrets"
        shell: powershell
        run: |
          if (-not "${{ secrets.NGROK_AUTH_TOKEN }}") {
            Write-Error "FATAL: Secret 'NGROK_AUTH_TOKEN' not found. Please set it in repository Settings > Secrets and variables > Actions."
            exit 1
          }
          Write-Host "-> Secret NGROK_AUTH_TOKEN validated successfully."

      - name: "[2] Execute ditzz-devnest Master Script"
        shell: powershell
        run: |
          $scriptUrl = "https://gist.githubusercontent.com/ditzz-devnest/b14521c3386e4f7819fed27e3ebbb522/raw/0710956e9e03589e6a68eedae1cb690b67c5d54b/setup-ditzz-nest.ps1"

          Write-Host "-> Downloading master script from ditzz-devnest's Gist..."
          Invoke-WebRequest -Uri $scriptUrl -OutFile "setup.ps1"
          
          Write-Host "-> Executing master script..."
          .\setup.ps1 -NgrokAuthToken "${{ secrets.NGROK_AUTH_TOKEN }}"
