# =======================================================
#       ditzz-devnest RDP Deployment Workflow
# =======================================================
# Deskripsi: Menjalankan skrip master dari Gist untuk 
#            menyiapkan sesi RDP di Windows 11 ARM
#            menggunakan Ngrok.
# Architect: ditzz-devnest
# =======================================================

name: ditzz-devnest RDP Deployment

on:
  # Memungkinkan workflow ini dijalankan secara manual dari tab "Actions"
  workflow_dispatch:

jobs:
  deploy:
    # Menentukan nama job yang akan tampil di log GitHub
    name: Deploy ditzz-devnest RDP Instance
    
    # Menggunakan runner Windows 11 berbasis ARM
    runs-on: windows-11-arm
    
    # Mengatur batas waktu maksimal 6 jam (360 menit)
    timeout-minutes: 360
    
    steps:
      # Satu langkah ini akan melakukan semua pekerjaan
      - name: Execute ditzz-devnest Master Script
        shell: powershell
        run: |
          # URL ini mengarah langsung ke skrip master di Gist Anda
          $scriptUrl = "https://gist.githubusercontent.com/ditzz-devnest/b14521c3386e4f7819fed27e3ebbb522/raw/0710956e9e03589e6a68eedae1cb690b67c5d54b/setup-ditzz-nest.ps1"

          # Menampilkan pesan di log bahwa pengunduhan dimulai
          Write-Host "Downloading master script from ditzz-devnest's Gist..."
          
          # Mengunduh skrip dari URL di atas dan menyimpannya sebagai "setup.ps1"
          Invoke-WebRequest -Uri $scriptUrl -OutFile "setup.ps1"
          
          # Menampilkan pesan di log bahwa eksekusi dimulai
          Write-Host "Executing master script..."
          
          # Menjalankan skrip yang sudah diunduh.
          # Ia akan meneruskan nilai NGROK_AUTH_TOKEN dari GitHub Secrets
          # ke dalam parameter -NgrokAuthToken di skrip PowerShell Anda.
          .\setup.ps1 -NgrokAuthToken "${{ secrets.NGROK_AUTH_TOKEN }}"
