# =======================================================
#       ditzz-devnest RDP Deployment Workflow v2.1
# =======================================================
# Deskripsi: Versi final yang menggunakan skrip master 
#            pribadi dari Gist dengan perbaikan koneksi Ngrok.
# Architect: ditzz-devnest
# =======================================================

name: ditzz-devnest RDP Deployment (Final)

on:
  workflow_dispatch:
    inputs:
      INSTANCE_LABEL:
        description: 'Label untuk sesi RDP ini (opsional)'
        required: false
        default: 'default'

jobs:
  deploy:
    name: "Deploy RDP Instance [${{ github.event.inputs.INSTANCE_LABEL }}]"
    runs-on: windows-11-arm
    timeout-minutes: 360
    
    steps:
      - name: "[1] Validate Secrets"
        shell: powershell
        run: |
          if (-not "${{ secrets.NGROK_AUTH_TOKEN }}") {
            Write-Error "FATAL: Secret 'NGROK_AUTH_TOKEN' tidak ditemukan. Harap atur di Settings > Secrets and variables > Actions."
            exit 1
          }
          Write-Host "-> Secret NGROK_AUTH_TOKEN berhasil divalidasi."

      - name: "[2] Execute ditzz-devnest Master Script"
        shell: powershell
        run: |
          # URL final yang mengarah ke skrip Gist Anda yang sudah diperbaiki
          $scriptUrl = "https://gist.githubusercontent.com/ditzz-dev/24c4253178c7b7018357b6393e2d505f/raw/771883a589c44db0d9d027afbfd1061e3c6140d2/devnest-win11.ps1"
          Write-Host "-> Mengunduh skrip master dari ditzz-devnest..."
          Invoke-WebRequest -Uri $scriptUrl -OutFile "setup.ps1"
          
          Write-Host "-> Menjalankan skrip master..."
          .\setup.ps1 -NgrokAuthToken "${{ secrets.NGROK_AUTH_TOKEN }}"
