# -----------------------------------------------------------------------------------
#            ditzz RDP | Powered by ditzz-devnest
# -----------------------------------------------------------------------------------
# Deskripsi:
# Alur kerja ini akan menyiapkan sebuah runner GitHub Actions dengan sistem operasi
# Windows 11 ARM, mengaktifkan Remote Desktop Protocol (RDP), dan membuat sebuah
# tunnel aman menggunakan Ngrok. Anda akan mendapatkan kredensial untuk login.
#
# Cara Menjalankan:
# 1. Buka tab "Actions" di repositori GitHub Anda.
# 2. Pilih alur kerja "🚀 ditzz RDP (Ngrok | Win11-ARM)" dari daftar.
# 3. Klik tombol "Run workflow", lalu klik "Run workflow" lagi.
# 4. Tunggu hingga proses berjalan dan lihat output di langkah "✅ Tampilkan Info Koneksi".
# -----------------------------------------------------------------------------------

name: "🚀 ditzz RDP (Ngrok | Win11-ARM)"

on:
  workflow_dispatch:

jobs:
  rdp-session:
    name: "🖥️ Windows 11 ARM | RDP Session"
    runs-on: windows-11-arm
    timeout-minutes: 360 # Batas waktu maksimal agar sesi tidak terputus

    steps:
      - name: "┌ 📝 Parameter Sesi"
        shell: pwsh
        run: |
          Write-Host "==========================================================================" -ForegroundColor Green
          Write-Host "             🚀 Memulai Sesi RDP untuk ditzz-devnest" -ForegroundColor Cyan
          Write-Host "=========================================================================="
          Write-Host "🔹 Sistem Operasi : Windows 11 ARM"
          Write-Host "🔹 Metode Akses   : RDP via Ngrok TCP Tunnel"
          Write-Host "🔹 Aktor          : ${{ github.actor }}"
          Write-Host "🔹 Repositori     : ${{ github.repository }}"
          Write-Host "=========================================================================="

      - name: "├ 🔐 Validasi Ngrok Auth Token"
        shell: pwsh
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          if (-not $env:NGROK_AUTH_TOKEN) {
            Write-Error "❌ Secret 'NGROK_AUTH_TOKEN' tidak ditemukan!"
            Write-Error "Harap tambahkan secret tersebut di pengaturan repositori Anda."
            exit 1
          }
          Write-Host "✅ Secret Ngrok berhasil divalidasi." -ForegroundColor Green
          
      - name: "├ ⚙️ Konfigurasi RDP dan Buat Pengguna"
        shell: pwsh
        run: |
          Write-Host "🔐 Membuat kata sandi yang aman untuk pengguna RDP..."
          # Membuat kata sandi acak dengan 16 karakter
          $password = -join ((65..90) + (97..122) + (48..57) | Get-Random -Count 16 | ForEach-Object { [char]$_ })
          $securePass = ConvertTo-SecureString $password -AsPlainText -Force
          
          Write-Host "👤 Membuat pengguna 'ditzz' dan menambahkannya ke grup Administrator..."
          New-LocalUser -Name "ditzz" -Password $securePass -FullName "ditzz-devnest" -Description "Temporary RDP User"
          Add-LocalGroupMember -Group "Administrators" -Member "ditzz"
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "ditzz"
          
          Write-Host "✅ Pengguna 'ditzz' berhasil dibuat." -ForegroundColor Green
          
          echo "RDP_PASSWORD=$password" >> $env:GITHUB_ENV

          Write-Host "🔧 Mengaktifkan Remote Desktop dan membuka port firewall..."
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
          netsh advfirewall firewall add rule name="Allow RDP" dir=in action=allow protocol=TCP localport=3389
          
          Write-Host "✅ Konfigurasi RDP dan Firewall selesai." -ForegroundColor Green

      - name: "├  tunnel 🌐 Instal Ngrok dan Buat Tunnel"
        shell: pwsh
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          Write-Host "📥 Mengunduh Ngrok Agent untuk ARM64..."
          Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-arm64.zip" -OutFile "ngrok.zip"
          Expand-Archive ngrok.zip
          
          Write-Host "🔑 Mengautentikasi Ngrok..."
          .\ngrok.exe config add-authtoken $env:NGROK_AUTH_TOKEN
          
          Write-Host "🚀 Memulai Ngrok TCP Tunnel untuk port 3389..."
          Start-Process -FilePath ".\ngrok.exe" -ArgumentList "tcp 3389 --log=stdout" -NoNewWindow
          
          Write-Host "✅ Ngrok Tunnel berhasil dimulai di background." -ForegroundColor Green
          
      - name: "└ ✅ Tampilkan Info Koneksi & Jaga Sesi"
        shell: pwsh
        run: |
          Write-Host "⏳ Menunggu Ngrok Tunnel siap (10 detik)..."
          Start-Sleep -s 10
          
          # Mengambil URL dari API lokal Ngrok
          $tunnels = Invoke-RestMethod -Uri "http://127.0.0.1:4040/api/tunnels"
          $tcpTunnel = $tunnels.tunnels | Where-Object { $_.proto -eq 'tcp' }
          if (!$tcpTunnel) {
              Write-Error "❌ Gagal mendapatkan alamat Ngrok Tunnel!"
              exit 1
          }
          
          $rdpAddress = $tcpTunnel.public_url.Replace("tcp://", "")
          
          Write-Host "==========================================================================" -ForegroundColor Green
          Write-Host "                       ✅ SESI RDP ANDA SIAP ✅" -ForegroundColor Cyan
          Write-Host "=========================================================================="
          Write-Host "💻 Alamat RDP      : $rdpAddress" -ForegroundColor White
          Write-Host "👤 Nama Pengguna   : ditzz" -ForegroundColor White
          Write-Host "🔑 Kata Sandi      : ${{ env.RDP_PASSWORD }}" -ForegroundColor White
          Write-Host "=========================================================================="
          Write-Host "Gunakan informasi di atas untuk terhubung menggunakan Remote Desktop Client." -ForegroundColor Yellow
          Write-Host "Sesi ini akan tetap aktif hingga Anda membatalkan alur kerja secara manual." -ForegroundColor Yellow
          
          # Loop tak terbatas untuk menjaga runner tetap aktif
          while ($true) {
              $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
              Write-Host "[$timestamp] Sesi RDP aktif. Tekan 'Cancel workflow' untuk menghentikan."
              Start-Sleep -Seconds 300
          }
