# -----------------------------------------------------------------------------------
#            ditzz RDP | Powered by ditzz-devnest (v4 - Robust Tailscale)
# -----------------------------------------------------------------------------------
# Deskripsi:
# Alur kerja ini menggunakan Tailscale untuk membuat koneksi RDP yang aman,
# andal, dan bersih ke runner Windows 11 ARM.
#
# Prasyarat:
# 1. Buat secret GitHub bernama `TAILSCALE_AUTH_KEY`.
# 2. Nilai secret HARUS berupa "Ephemeral" dan "Pre-authorized" Auth Key
#    dari konsol admin Tailscale Anda.
# -----------------------------------------------------------------------------------

name: "🚀 ditzz RDP (Tailscale | Win11-ARM)"

on:
  workflow_dispatch:

jobs:
  rdp-session:
    name: "🖥️ Windows 11 ARM | RDP via Tailscale"
    runs-on: windows-11-arm
    timeout-minutes: 360

    steps:
      - name: "┌ 📝 Parameter Sesi"
        shell: pwsh
        run: |
          Write-Host "==========================================================================" -ForegroundColor Green
          Write-Host "         🚀 Memulai Sesi RDP untuk ditzz-devnest via Tailscale" -ForegroundColor Cyan
          Write-Host "=========================================================================="
          Write-Host "🔹 Sistem Operasi : Windows 11 ARM"
          Write-Host "🔹 Metode Akses   : RDP via Tailscale Private Network"
          Write-Host "🔹 Aktor          : ${{ github.actor }}"
          Write-Host "🔹 Repositori     : ${{ github.repository }}"
          Write-Host "=========================================================================="

      - name: "├ 🔐 Validasi Tailscale Auth Key"
        shell: pwsh
        env:
          TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
        run: |
          if (-not $env:TAILSCALE_AUTH_KEY) {
            Write-Error "❌ Secret 'TAILSCALE_AUTH_KEY' tidak ditemukan!"
            exit 1
          }
          Write-Host "✅ Secret Tailscale berhasil divalidasi." -ForegroundColor Green
          
      - name: "├ ⚙️ Konfigurasi RDP dan Buat Pengguna"
        shell: pwsh
        run: |
          Write-Host "🔐 Membuat kata sandi yang aman untuk pengguna RDP..."
          $password = -join ((65..90) + (97..122) + (48..57) | Get-Random -Count 16 | ForEach-Object { [char]$_ })
          $securePass = ConvertTo-SecureString $password -AsPlainText -Force
          
          Write-Host "👤 Membuat pengguna 'ditzz' dan menambahkannya ke grup Administrator..."
          New-LocalUser -Name "ditzz" -Password $securePass -FullName "ditzz-devnest"
          Add-LocalGroupMember -Group "Administrators" -Member "ditzz"
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "ditzz"
          
          Write-Host "✅ Pengguna 'ditzz' berhasil dibuat." -ForegroundColor Green
          echo "RDP_PASSWORD=$password" >> $env:GITHUB_ENV

          Write-Host "🔧 Mengaktifkan Remote Desktop dan membuka port firewall..."
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
          netsh advfirewall firewall add rule name="Allow RDP" dir=in action=allow protocol=TCP localport=3389
          
          Write-Host "✅ Konfigurasi RDP dan Firewall selesai." -ForegroundColor Green

      - name: "├ 🌐 Instal & Konfigurasi Tailscale"
        shell: pwsh
        env:
          TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
        run: |
          Write-Host "📥 Mengunduh versi terbaru Tailscale..."
          # Menggunakan URL yang selalu menunjuk ke versi stabil terbaru
          Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-latest.msi" -OutFile "tailscale.msi"
          
          Write-Host "⚙️ Menginstal Tailscale..."
          Start-Process msiexec.exe -ArgumentList "/i tailscale.msi /quiet" -Wait
          
          # Membuat hostname unik untuk runner ini
          $hostname = "gh-runner-ditzz-${{ github.run_number }}"
          echo "TS_HOSTNAME=$hostname" >> $env:GITHUB_ENV
          
          Write-Host "🚀 Menghubungkan ke Tailscale dengan hostname '$hostname'..."
          & "C:\Program Files\Tailscale\tailscale.exe" up --authkey="$env:TAILSCALE_AUTH_KEY" --hostname="$hostname" --accept-routes

          Write-Host "✅ Perintah koneksi Tailscale telah dieksekusi." -ForegroundColor Green
          
      - name: "└ ✅ Verifikasi Koneksi & Tampilkan Info"
        shell: pwsh
        run: |
          $max_retries = 12
          $retry_delay_seconds = 5
          $ts_ip = $null

          Write-Host "📡 Memverifikasi koneksi Tailscale..."
          for ($i = 1; $i -le $max_retries; $i++) {
              $status = (& "C:\Program Files\Tailscale\tailscale.exe" status --json | ConvertFrom-Json)
              if ($status.BackendState -eq "Running" -and $status.Self.Online) {
                  $ts_ip = $status.Self.TailscaleIPs[0]
                  Write-Host "✅ Koneksi Tailscale stabil dan online (IP: $ts_ip)." -ForegroundColor Green
                  break
              }
              if ($i -lt $max_retries) {
                  Write-Host "Percobaan $i: Koneksi belum siap. Menunggu $retry_delay_seconds detik..."
                  Start-Sleep -Seconds $retry_delay_seconds
              } else {
                  Write-Error "❌ Gagal mendapatkan koneksi Tailscale yang stabil setelah $max_retries percobaan."
                  exit 1
              }
          }
          
          Write-Host "==========================================================================" -ForegroundColor Green
          Write-Host "                       ✅ SESI RDP ANDA SIAP ✅" -ForegroundColor Cyan
          Write-Host "=========================================================================="
          Write-Host "Gunakan salah satu alamat di bawah ini untuk terhubung:"
          Write-Host "💻 Alamat IP       : $ts_ip" -ForegroundColor White
          Write-Host "🖥️  Hostname        : ${{ env.TS_HOSTNAME }}" -ForegroundColor White
          Write-Host "--------------------------------------------------------------------------"
          Write-Host "👤 Nama Pengguna   : ditzz" -ForegroundColor White
          Write-Host "🔑 Kata Sandi      : ${{ env.RDP_PASSWORD }}" -ForegroundColor White
          Write-Host "=========================================================================="
          
          while ($true) {
              $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
              Write-Host "[$timestamp] Sesi RDP aktif. Tekan 'Cancel workflow' untuk menghentikan."
              Start-Sleep -Seconds 300
          }
